name = "cloudflare"
type = "javascript"

account_id = "b9049bb55ece84a751d35c90b4242bf0"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-12"

[env.production]
zone_id = "a1363ec6f6f2e6f2776ce84672d44d33"
route = "binaries.link/*"
